// sy_
const PREFIX = 'sw_';

export const TABLE_NAMES = {
  auth: `${PREFIX}auth`,
  // active: `sy_${PREFIX}active`,
  attribute: `${PREFIX}attribute`,
  attribute_description: `${PREFIX}attribute_description`,
  attribute_value: `${PREFIX}attribute_value`,
  attribute_value_description: `${PREFIX}attribute_value_description`,
  category: `${PREFIX}category`,
  category_description: `${PREFIX}category_description`,
  category_path: `${PREFIX}category_path`,
  category_rules: `${PREFIX}category_rules`,
  color_first: `${PREFIX}color_first`,
  color_first_description: `${PREFIX}color_first_description`,
  color_3: `${PREFIX}color_3`,
  color_3_description: `${PREFIX}color_3_description`,
  color_code: `${PREFIX}color_code`,
  color_code_description: `${PREFIX}color_code_description`,
  fabric: `${PREFIX}fabric`,
  fabric_description: `${PREFIX}fabric_description`,
  fabric_composition: `${PREFIX}fabric_composition`,
  fabric_composition_description: `${PREFIX}fabric_composition_description`,
  fabric_composition_item: `${PREFIX}fabric_composition_item`,
  fabric_composition_item_description: `${PREFIX}fabric_composition_item_description`,
  fabric_composition_sub: `${PREFIX}fabric_composition_sub`,
  gender: `${PREFIX}gender`,
  gender_description: `${PREFIX}gender_description`,
  group_item: `${PREFIX}group_item`,
  item_type: `${PREFIX}item_type`,
  item_type_description: `${PREFIX}item_type_description`,
  language: `${PREFIX}language`,
  model_item_size: `${PREFIX}model_item_size`,
  menu: `${PREFIX}menu`,
  menu_description: `${PREFIX}menu_description`,
  menu_path: `${PREFIX}menu_path`,
  new_item: `${PREFIX}new_item`,
  photo_update: `${PREFIX}photo_update`,
  product: `${PREFIX}product`,
  product_attributes: `${PREFIX}product_attributes`,
  product_category: `${PREFIX}product_category`,
  product_description: `${PREFIX}product_description`,
  product_images: `${PREFIX}product_images`,
  product_special: `${PREFIX}product_special`,
  product_stickers: `${PREFIX}product_stickers`,
  size: `${PREFIX}size`,
  shablon: `${PREFIX}shablon`,
  task: `${PREFIX}tasks`,
  user: `${PREFIX}users`,
};
