export const TABLE_NAMES = {
  auth: 'auth',
  shablon: 'shablon',
  active: 'active',
  attribute: 'attribute',
  attribute_description: 'attribute_description',
  attribute_value: 'attribute_value',
  attribute_value_description: 'attribute_value_description',
  category: 'category',
  category_description: 'category_description',
  category_path: 'category_path',
  menu: 'menu',
  menu_description: 'menu_description',
  menu_path: 'menu_path',
  product: 'product',
  product_attributes: 'product_attributes',
  product_category: 'product_category',
  product_description: 'product_description',
  product_images: 'product_images',
  product_special: 'product_special',
  product_stickers: 'product_stickers',
  user: 'users',
};
